# RustySquid clippy configuration
msrv = "1.70.0"
cognitive-complexity-threshold = 30
too-many-lines-threshold = 150
too-many-arguments-threshold = 7
type-complexity-threshold = 250
single-char-binding-names-threshold = 4
trivial-copy-size-limit = 128
pass-by-value-size-limit = 256
enum-variant-size-threshold = 200
future-size-threshold = 16384
unnecessary-box-size = 128